---
Name: "dr-register-endpoint"
Description: "Register Digital Rebar Server as Endpoint"
Documentation: |
  Registers the system as a managed endpoint by the Multi-Site Manager  
ExtraClaims:
  - scope: "endpoints"
    action: "*"
    specific: "*"
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2020

      set -e
      {{template "setup.tmpl" .}}

      manager="$(drpcli info get | jq -r .manager)"
      if [[ "$manager" == "true" ]] ; then

        {{ if .ParamExists "dr-server/install-drpid" }}
        DRPID={{ regexFind "[a-zA-Z0-9-]+" (.Param "dr-server/install-drpid") }}
        {{ else }}
        DRPID="{{ regexFind "[a-zA-Z0-9-]+" (list "site" .Machine.Name | join "-") }}"
        {{ end }}

        if drpcli endpoints exists $DRPID >/dev/null ; then
          echo "Endpoint $DRPID already registered in Manager"
        else
          echo "Manager, register new endpoint $DRPID (from machine {{.Machine.Name}})"
          drpcli endpoints create "{\"Id\":\"$DRPID\",
            \"Params\":{\"manager/url\": \"https://{{ .Machine.Address }}:8092\"},
            \"Meta\":{{ .Machine.Meta | toJson }} }" > /dev/null
          drpcli endpoints set $DRPID param "manager/username" to "{{ .Param "dr-server/initial-user" }}" > /dev/null
          drpcli endpoints set $DRPID param "manager/password" to "{{ .Param "dr-server/initial-password" }}" > /dev/null
  
          echo "let's let things settle for 30 seconds"
          sleep 30
        fi

        if [[ "$(drpcli endpoints show $DRPID | jq -r .Available)" == "true" ]]; then
          echo "Yes: Endpoint $DRPID is Available."
        else
          echo "WARNING: Endpoint $DRPID is NOT available"
        fi

      else
        echo "Not a manager, no action"
      fi

      exit 0
    Name: "drp-reguster"
Meta:
  icon: "chess"
  color: "purple"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
