---
Name: "dr-server-seed"
Description: "Setup Files for Digital Rebar Server"
Documentation: |
  Copy Files from Multi-Site-Manager to Local DR Server
ExtraClaims:
  - scope: "files"
    action: "*"
    specific: "*"
  - scope: "contexts"
    action: "*"
    specific: "*"
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2020

      set -e
      {{template "setup.tmpl" .}}

      # local endpoint
      echo "Collecting info from manager"

      echo "Pointing DRPCLI to Proxy Endpoint $EPID"
      EPID={{ .Machine.Name }}

      if drpcli -u $EPID contexts exists runner ; then
        echo "skipping: runner context already installed"
      else
        echo "adding local runner context"
        drpcli contexts show runner > runner.json
        drpcli -u $EPID contexts create - < runner.json  > /dev/null
      fi

      echo "BACKUP APPROACH: Populate the contexts from local"
      raw=$(drpcli contexts list Engine=docker-context)
      contexts=$(jq -r ".[].Name" <<< "${raw}")
      i=0
      for context in $contexts; do
        image=$(jq -r ".[$i].Image" <<< "${raw}")
        if drpcli -u $EPID files exists contexts/docker-context/${image} ; then
          echo "skipping: $context already uploaded"
        else
          echo "Installing Container for $context named from $image"
          drpcli -u $EPID files upload {{ .ProvisionerURL }}/files/contexts/docker-context/${image} as contexts/docker-context/${image} > /dev/null
        fi
        i=$(($i + 1))
      done

      echo "done"
      exit 0
    Name: "drp-install"
Meta:
  icon: "heart"
  color: "green"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
