---
Description: "Setup Edge Machines"
Name: "edge-machines"
ExtraClaims:
  - scope: "machines"
    action: "*"
    specific: "*"
  - scope: "profiles"
    action: "*"
    specific: "*"
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2020

      set -e
      {{template "setup.tmpl" .}}

      if drpcli profiles exists {{ .Machine.Name }} ; then
        echo "eponymous profile exists"
      else
        echo "creating eponymous profile"
        drpcli profiles create '{"Name":"{{.Machine.Name}}", 
          "Params":{"cluster/profile":"{{.Machine.Name}}"},
          "Meta":{"icon":"map marker"}
        }' > /dev/null
        drpcli machines addprofile $RS_UUID "{{.Machine.Name}}"  > /dev/null
      fi

      echo "reviewing machines {{ .Param "demo/machines" }}"
      for mc in {{ .Param "demo/machines" }}
      do
        machine="{{ .Param "demo/cluster-prefix" }}-{{ .Param "linode/region" }}-$mc"
        if drpcli machines exists Name:$machine; then
          echo "  $machine exists, updating workflow"
          drpcli machines workflow Name:$machine "{{ .Param "demo/workflow" }}"  > /dev/null
        else
          echo "  no $machine, creating it"
          drpcli machines create "{\"Name\":\"${machine}\", \
            \"Workflow\":\"{{ .Param "demo/workflow" }}\", \
            \"Profiles\":[\"linode\",\"{{ .Machine.Name }}\"], \
            \"Description\":\"Edge Server\", \
            \"Meta\":{\"BaseContext\":\"drpcli-runner\", \"color\":\"{{ .Param "demo/cluster-color" }}\", \"icon\":\"star\"}}" >/dev/null
        fi
      done

      echo "Edge Machines Created"
      exit 0

    Name: "edge-machines"
Meta:
  icon: "server"
  color: "yellow"
  title: "Digital Rebar Community Content"
  feature-flags: "sane-exit-codes"
